### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-DuilioAquino10#2]
[Aquino Lopez Duilio Ruben - prac2.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-DuilioAquino10/files/6338667/Aquino.Lopez.Duilio.Ruben.-.prac2.pdf)

**Comment by Band-hi** [comment]
Practica 87/100
Calificación 17.4/20

-Falta subir el código a GitHub
-Falta agregar objetivo de la practica, material.
-Falta listar mas imágenes.
-Faltan líneas en la conclusión.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
